namespace PipServices3.Commons.Validate
{
    /// <summary>
    /// Types of validation results generated by validation schemas.
    /// </summary>
    /// See <see cref="ValidationResult"/>
    public enum ValidationResultType : int
    {
        /** General information (not an error). */
        Information = 0,
        /** Warning about something suspecious. In strict mode is treated as error */
        Warning = 1,
        /** Validation error. */
        Error = 2
    }
}
